### ISSUE TITLE
Install Octobox in Centos 7 server

### ISSUE THREAD

**Issue by thomas-illiet** [octobox/octobox#1138]
Hello guys :)

In tried to install Octobox on a server Centos 7 !

when i start the application i have this screen :
![image](https://user-images.githubusercontent.com/2133666/47291222-1f1c6280-d603-11e8-9aa7-6cbe8e56538f.png)

And i have this in the console :
```
[cloud-user@70b1fdae-6ef5-4e3d-af9e-5428169acb8c octobox]$ rails s
=> Booting Puma
=> Rails 5.2.1 application starting in development
=> Run `rails server -h` for more startup options
[3810] Puma starting in cluster mode...
[3810] * Version 3.12.0 (ruby 2.5.3-p105), codename: Llamas in Pajamas
[3810] * Min threads: 5, max threads: 5
[3810] * Environment: development
[3810] * Process workers: 1
[3810] * Preloading application
[3810] * Listening on tcp://0.0.0.0:3000
[3810] Use Ctrl-C to stop
[3810] - Worker 0 (pid: 3851) booted, phase: 0
Started GET "/" for 184.53.1.84 at 2018-10-22 11:58:48 +0000
Cannot render console from 184.53.1.84! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
   (0.6ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
  ↳ /home/cloud-user/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.2.1/lib/active_record/log_subscriber.rb:98
Processing by NotificationsController#index as HTML
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 155], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:51
  CACHE User Load (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 155], ["LIMIT", 1]]
  ↳ app/controllers/application_controller.rb:51
  Rendering pages/home.html.erb within layouts/application
  Rendered pages/home.html.erb within layouts/application (830.6ms)
Completed 500 Internal Server Error in 860ms (ActiveRecord: 3.1ms | SQL count: 5)


Not notifying due to an invalid api_key

ActionView::Template::Error (TypeError: Object #<Object> has no method 'sign'):
    1: <div class="container mt-5">
    2:   <h1 class="text-center"><%= octobox_round(80) %> Octobox</h1>
    3:   <p class="text-center">Untangle your GitHub Notifications</p>
    4:   <div class="text-center ">
    5:     <%= image_tag 'screenshot.png', class: 'screenshot', alt: 'Octobox Screenshot' %>

(execjs):1:777
app/helpers/application_helper.rb:39:in `octobox_round'
app/views/pages/home.html.erb:2:in `_app_views_pages_home_html_erb__4331463890829283298_47328592164440'
app/controllers/notifications_controller.rb:338:in `block (2 levels) in authenticate_web_or_api!'
app/controllers/notifications_controller.rb:337:in `authenticate_web_or_api!'
```

To solve this problem I try to use the older version of Octabox or reinstall centos server....

Do you have an idea for this problem?

Thx
Thomas

**Comment by andrew** [comment]
I think you need to update the version of node.js on your server, our docs are pretty lacking on that requirement.

**Comment by thomas-illiet** [comment]
THx @andrew  !

to install octobox in centos :

```
yum install postgresql postgresql-server postgresql-contrib libpqxx-devel libpqxx
yum install mysql-devel

sudo postgresql-setup initdb
Config : /var/lib/pgsql/data/pg_hba.conf - md5
sudo systemctl start postgresql
sudo systemctl enable postgresql

sudo -i -u postgres psql
create user 'cloud-user';
alter user 'cloud-user' with encrypted password 'XXXXXXXXXXXXXXX';
ALTER USER cloud-user'WITH SUPERUSER;

yum install nodejs
gem install rails

yum install redis
sudo systemctl start redis
sudo systemctl enable redis
```

thx
