### ISSUE TITLE
How to serve static assets using Nginx

### ISSUE THREAD

**Issue by AdrienKuhn** [octobox/octobox#2012]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance

### Summary of Problem

I'm trying to deploy my own Octobox instance using Docker following https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md.
I receive a 500 error for all assets when `RAILS_ENVIRONMENT` variable is set to `production`:

```
app_1    | Error during failsafe response: ActionController::UnknownFormat
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/mime_responds.rb:216:in `respond_to'
app_1    |   /usr/src/app/app/controllers/application_controller.rb:43:in `authenticate_user!'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:429:in `block in make_lambda'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:202:in `block in halting'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:514:in `block in invoke_before'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:514:in `each'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:514:in `invoke_before'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:134:in `run_callbacks'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:41:in `process_action'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/rescue.rb:22:in `process_action'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `block in instrument'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `instrument'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
app_1    |   /usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/base.rb:136:in `process'
app_1    |   /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/rendering.rb:39:in `process'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal.rb:191:in `dispatch'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal.rb:252:in `dispatch'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:33:in `serve'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:49:in `block in serve'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `each'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `serve'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:837:in `call'
app_1    |   /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/probes/action_dispatch/routing/route_set.rb:14:in `block in call'
app_1    |   /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/fanout.rb:25:in `instrument'
app_1    |   /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/probes/action_dispatch/routing/route_set.rb:13:in `call'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
app_1    |   /usr/local/bundle/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
app_1    |   /usr/local/bundle/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `block in call'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `block in tagged'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:28:in `tagged'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `tagged'
app_1    |   /usr/local/bundle/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `call'
app_1    |   /usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
app_1    |   /usr/local/bundle/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
app_1    |   /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
app_1    |   /usr/local/bundle/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
app_1    |   /usr/local/bundle/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
app_1    |   /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
app_1    |   /usr/local/bundle/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
app_1    |   /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
app_1    |   /usr/local/bundle/gems/hirefire-resource-0.7.2/lib/hirefire/middleware.rb:38:in `call'
app_1    |   /usr/local/bundle/gems/railties-6.0.0/lib/rails/engine.rb:526:in `call'
app_1    |   /usr/local/bundle/gems/puma-4.1.0/lib/puma/configuration.rb:228:in `call'
app_1    |   /usr/local/bundle/gems/puma-4.1.0/lib/puma/server.rb:664:in `handle_request'
app_1    |   /usr/local/bundle/gems/puma-4.1.0/lib/puma/server.rb:467:in `process_client'
app_1    |   /usr/local/bundle/gems/puma-4.1.0/lib/puma/server.rb:328:in `block in run'
app_1    |   /usr/local/bundle/gems/puma-4.1.0/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

Everything is working fine when I set the environment variable to `development`.
Could we have an example of how to serve static assets using Nginx?

### Steps to Reproduce the Issue

- In local environment, add this to the docker-compose file

```
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ${PWD}/default.conf:/etc/nginx/conf.d/default.conf
```

- Create nginx config file

```
# default.conf

server {
  listen 80;
  server_name _;
  location / {
    proxy_set_header Host $proxy_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://app:3000;
  }
}
```

- Set `RAILS_ENVIRONMENT` to `production`

- Go to http://localhost:8080

### Versions, Operating System and Hardware

- Which version/commit of Octobox are you using? Latest
- Which browser are you accessing Octobo with? Firefox/Chrome
- Windows? Linux? Mac? N/A
- How are you deploying Octobox (Docker, Heroku, Openshift, etc) Docker

**Comment by AdrienKuhn** [comment]
I found the solution with [this PR](https://github.com/octobox/octobox/pull/1141/files#diff-dfc19360b7215500c58a8fc7931ce047R45)

**Comment by null-dev** [comment]
For anyone else getting that `ActionController::UnknownFormat` error: That error occurs as the app does not serve static files by default when `RAILS_ENVIRONMENT=production`, causing static file requests to be handled by the wrong handler.

To fix it, you can:

- Configure `nginx` to serve the static files like AdrienKuhn did ^
- **OR** set this environment variable: `RAILS_SERVE_STATIC_FILES=1` to tell the app to serve static files
