### ISSUE TITLE
Archiving/Marking as read leads to an error message

### ISSUE THREAD

**Issue by rhuss** [octobox/octobox#2014]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [X] My instance
 
🐞 **Problem**

When trying to archive/mark as read by selecting issues via checkboxes and pressing the corresponding buttons, I get the following error:

![grafik](https://user-images.githubusercontent.com/99080/64491704-d3e75e80-d26b-11e9-97b9-9c35554e484d.png)

The server returns the following error as response to the POST request:

<details>
<summary>Error Message</summary> 

```
SidekiqUniqueJobs::ScriptError in NotificationsController#archive_selected

Problem compiling lock. Message: ERR Error running script (call to f_4f10234d9598472dce939a378cc0aac09b78f860): @user_script:27: @user_script: 27: -MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
Extracted source (around line #93):

#91       end
#92 
*93       raise ScriptError, file_name: file_name, source_exception: ex
#94     end
#95 
#96     #

Extracted source (around line #36):

#34       execute_script(file_name, redis_pool, options)
#35     rescue Redis::CommandError => ex
*36       handle_error(ex, file_name) do
#37         call(file_name, redis_pool, options)
#38       end
#39     end

Extracted source (around line #33):

#31     # @return value from script
#32     #
*33     def call(file_name, redis_pool, options = {})
#34       execute_script(file_name, redis_pool, options)
#35     rescue Redis::CommandError => ex
#36       handle_error(ex, file_name) do


Rails.root: /usr/src/app

Application Trace
config/initializers/custom_sidekiq_worker.rb:5:in `perform_async_if_configured'
app/models/notification.rb:94:in `mark_read'
app/models/notification.rb:87:in `archive'
app/controllers/notifications_controller.rb:191:in `archive_selected'

Framework Trace
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/scripts.rb:93:in `handle_error'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/scripts.rb:36:in `rescue in call'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/scripts.rb:33:in `call'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/locksmith.rb:54:in `lock'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/lock/base_lock.rb:29:in `lock'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/client/middleware.rb:43:in `block in locked?'
sidekiq (6.0.0) lib/sidekiq/logger.rb:16:in `with_context'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:39:in `with_context'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/client/middleware.rb:42:in `locked?'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/client/middleware.rb:37:in `success?'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/client/middleware.rb:27:in `call'
sidekiq (6.0.0) lib/sidekiq/middleware/chain.rb:131:in `block in invoke'
sidekiq (6.0.0) lib/sidekiq/middleware/chain.rb:134:in `invoke'
sidekiq (6.0.0) lib/sidekiq/client.rb:211:in `process_single'
sidekiq (6.0.0) lib/sidekiq/client.rb:71:in `push'
sidekiq (6.0.0) lib/sidekiq/worker.rb:243:in `client_push'
sidekiq (6.0.0) lib/sidekiq/worker.rb:200:in `perform_async'
actionpack (6.0.0) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.0) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.0) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.0) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.0) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.0) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
sql_queries_count (0.0.1) lib/sql_queries_count/controller_runtime.rb:14:in `process_action'
actionpack (6.0.0) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.0) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.0) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:837:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/builder.rb:64:in `call'
bullet (6.0.2) lib/bullet/rack.rb:12:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.0) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
bugsnag (6.12.1) lib/bugsnag/integrations/rack.rb:49:in `call'
better_errors (2.5.1) lib/better_errors/middleware.rb:59:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:19:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
railties (6.0.0) lib/rails/engine.rb:526:in `call'
puma (4.1.0) lib/puma/configuration.rb:228:in `call'
puma (4.1.0) lib/puma/server.rb:664:in `handle_request'
puma (4.1.0) lib/puma/server.rb:467:in `process_client'
puma (4.1.0) lib/puma/server.rb:328:in `block in run'
puma (4.1.0) lib/puma/thread_pool.rb:135:in `block in spawn_thread'

Full Trace
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/scripts.rb:93:in `handle_error'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/scripts.rb:36:in `rescue in call'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/scripts.rb:33:in `call'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/locksmith.rb:54:in `lock'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/lock/base_lock.rb:29:in `lock'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/client/middleware.rb:43:in `block in locked?'
sidekiq (6.0.0) lib/sidekiq/logger.rb:16:in `with_context'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/sidekiq_unique_jobs.rb:39:in `with_context'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/client/middleware.rb:42:in `locked?'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/client/middleware.rb:37:in `success?'
sidekiq-unique-jobs (6.0.13) lib/sidekiq_unique_jobs/client/middleware.rb:27:in `call'
sidekiq (6.0.0) lib/sidekiq/middleware/chain.rb:131:in `block in invoke'
sidekiq (6.0.0) lib/sidekiq/middleware/chain.rb:134:in `invoke'
sidekiq (6.0.0) lib/sidekiq/client.rb:211:in `process_single'
sidekiq (6.0.0) lib/sidekiq/client.rb:71:in `push'
sidekiq (6.0.0) lib/sidekiq/worker.rb:243:in `client_push'
sidekiq (6.0.0) lib/sidekiq/worker.rb:200:in `perform_async'
config/initializers/custom_sidekiq_worker.rb:5:in `perform_async_if_configured'
app/models/notification.rb:94:in `mark_read'
app/models/notification.rb:87:in `archive'
app/controllers/notifications_controller.rb:191:in `archive_selected'
actionpack (6.0.0) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.0) lib/abstract_controller/base.rb:196:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.0) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.0) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.0) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.0) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.0) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.0) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.0) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.0) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
sql_queries_count (0.0.1) lib/sql_queries_count/controller_runtime.rb:14:in `process_action'
actionpack (6.0.0) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.0) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.0) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.0) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.0) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.0) lib/action_dispatch/routing/route_set.rb:837:in `call'
omniauth (1.9.0) lib/omniauth/strategy.rb:192:in `call!'
omniauth (1.9.0) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.0) lib/omniauth/builder.rb:64:in `call'
bullet (6.0.2) lib/bullet/rack.rb:12:in `call'
rack (2.0.7) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.7) lib/rack/etag.rb:25:in `call'
rack (2.0.7) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.7) lib/rack/head.rb:12:in `call'
actionpack (6.0.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.7) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.7) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.0) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.0) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
bugsnag (6.12.1) lib/bugsnag/integrations/rack.rb:49:in `call'
better_errors (2.5.1) lib/better_errors/middleware.rb:59:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.1) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.1) lib/web_console/middleware.rb:19:in `block in call'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.1) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.0) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.7) lib/rack/method_override.rb:22:in `call'
rack (2.0.7) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
actionpack (6.0.0) lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
railties (6.0.0) lib/rails/engine.rb:526:in `call'
puma (4.1.0) lib/puma/configuration.rb:228:in `call'
puma (4.1.0) lib/puma/server.rb:664:in `handle_request'
puma (4.1.0) lib/puma/server.rb:467:in `process_client'
puma (4.1.0) lib/puma/server.rb:328:in `block in run'
puma (4.1.0) lib/puma/thread_pool.rb:135:in `block in spawn_thread'



Request parameters
{"id"=>["8712"],
 "value"=>"true",
 "repo"=>"funktionio/funktion-connectors"}

Session dump
_csrf_token: "HN67slJ3t82YqyiABxtQoxnGJafuuJ/OALtsRckgIX4="
session_id: "6e7f1c023c6e2eb7696a8877c5ae8f36"

Env dump
GATEWAY_INTERFACE: "CGI/1.2"
HTTP_ACCEPT: "*/*"
HTTP_ACCEPT_ENCODING: "gzip, deflate, br"
HTTP_ACCEPT_LANGUAGE: "en,de;q=0.7,en-US;q=0.3"
HTTP_CACHE_CONTROL: "no-cache"
HTTP_PRAGMA: "no-cache"
HTTP_VERSION: "HTTP/1.1"
HTTP_X_CSRF_TOKEN: "gr6ugP5EKnouEhAXjRsJLc4x16WhQESF0OEpAHXiRGSeYBUyrDOdt7a5OJeKAFmO1/fyAk/420vQWkVFvMJlGg=="
HTTP_X_FORWARDED_FOR: "79.221.54.145"
HTTP_X_FORWARDED_HOST: "app-octobox.6923.rh-us-east-1.openshiftapps.com"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "10.131.14.1"
SERVER_NAME: "app-octobox.6923.rh-us-east-1.openshiftapps.com"
SERVER_PROTOCOL: "HTTP/1.1"

Response headers
None
````

</details>

Interestlingly after this operation the selected notification are archived/marked as read despite the error message.

**Comment by rhuss** [comment]
My bad, it was because of a faulty Redi setup on OpenShift.

sorry for the noise.
