### ISSUE TITLE
Styling is not rendered (css, images)

### ISSUE THREAD

**Issue by glitchcrab** [octobox/octobox#2036]
Accessing Octobox results in an unstyled page.

Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance
 
🐞 **Problem**
Octobox container using the latest image from yesterday. Rails env is set to production and a sufficiently long secret_key_base is used. Note that the DB migrations work fine on initial launch, this issue hits once the UI is available.

Attempting to view the JS or CCS files directly result in a 500 error, container logs when the issue occurs:
```
Error during failsafe response: Missing template errors/not_found, application/not_found with {:locale=>[:en], :formats=>[:css], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/usr/src/app/app/views"

  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/path_set.rb:48:in `find'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/lookup_context.rb:129:in `find'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/renderer/template_renderer.rb:47:in `determine_template'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/renderer/template_renderer.rb:9:in `render'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/rendering.rb:118:in `block in _render_template'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/base.rb:304:in `in_rendering_context'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/rendering.rb:117:in `_render_template'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/streaming.rb:219:in `_render_template'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/rendering.rb:103:in `render_to_body'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/rendering.rb:25:in `render'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/rendering.rb:36:in `render'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
  /usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/core_ext/benchmark.rb:14:in `ms'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:85:in `cleanup_view_runtime'
  /usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/railties/controller_runtime.rb:39:in `cleanup_view_runtime'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:43:in `render'
  /usr/src/app/app/controllers/errors_controller.rb:4:in `not_found'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/base.rb:196:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:135:in `run_callbacks'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `block in instrument'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `instrument'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  /usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/base.rb:136:in `process'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/rendering.rb:39:in `process'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal.rb:191:in `dispatch'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal.rb:252:in `dispatch'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:33:in `serve'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:49:in `block in serve'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `each'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `serve'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:837:in `call'
  /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/probes/action_dispatch/routing/route_set.rb:14:in `block in call'
  /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/fanout.rb:25:in `instrument'
  /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/probes/action_dispatch/routing/route_set.rb:13:in `call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /usr/local/bundle/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  /usr/local/bundle/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `block in call'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `block in tagged'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:28:in `tagged'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `tagged'
  /usr/local/bundle/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `call'
  /usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:11:in `block in call'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/logger_silence.rb:36:in `silence'
  /usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:11:in `call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /usr/local/bundle/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
  /usr/local/bundle/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
  /usr/local/bundle/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /usr/local/bundle/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
  /usr/local/bundle/gems/hirefire-resource-0.7.2/lib/hirefire/middleware.rb:38:in `call'
  /usr/local/bundle/gems/railties-6.0.0/lib/rails/engine.rb:526:in `call'
  /usr/local/bundle/gems/puma-4.1.1/lib/puma/configuration.rb:228:in `call'
  /usr/local/bundle/gems/puma-4.1.1/lib/puma/server.rb:664:in `handle_request'
  /usr/local/bundle/gems/puma-4.1.1/lib/puma/server.rb:467:in `process_client'
  /usr/local/bundle/gems/puma-4.1.1/lib/puma/server.rb:328:in `block in run'
  /usr/local/bundle/gems/puma-4.1.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Error during failsafe response: Missing template errors/not_found, application/not_found with {:locale=>[:en], :formats=>[:svg], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/usr/src/app/app/views"

  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/path_set.rb:48:in `find'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/lookup_context.rb:129:in `find'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/renderer/template_renderer.rb:47:in `determine_template'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/renderer/template_renderer.rb:9:in `render'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/rendering.rb:118:in `block in _render_template'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/base.rb:304:in `in_rendering_context'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/rendering.rb:117:in `_render_template'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/streaming.rb:219:in `_render_template'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/rendering.rb:103:in `render_to_body'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/rendering.rb:25:in `render'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/rendering.rb:36:in `render'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
  /usr/local/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/core_ext/benchmark.rb:14:in `ms'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:85:in `cleanup_view_runtime'
  /usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/railties/controller_runtime.rb:39:in `cleanup_view_runtime'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:43:in `render'
  /usr/src/app/app/controllers/errors_controller.rb:4:in `not_found'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/base.rb:196:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:135:in `run_callbacks'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:41:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/rescue.rb:22:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `block in instrument'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `instrument'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  /usr/local/bundle/gems/activerecord-6.0.0/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/abstract_controller/base.rb:136:in `process'
  /usr/local/bundle/gems/actionview-6.0.0/lib/action_view/rendering.rb:39:in `process'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal.rb:191:in `dispatch'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_controller/metal.rb:252:in `dispatch'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:33:in `serve'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:49:in `block in serve'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `each'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `serve'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:837:in `call'
  /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/probes/action_dispatch/routing/route_set.rb:14:in `block in call'
  /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/fanout.rb:25:in `instrument'
  /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/probes/action_dispatch/routing/route_set.rb:13:in `call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:51:in `render_exception'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
  /usr/local/bundle/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
  /usr/local/bundle/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `block in call'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `block in tagged'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:28:in `tagged'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `tagged'
  /usr/local/bundle/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `call'
  /usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:11:in `block in call'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/logger_silence.rb:36:in `silence'
  /usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:11:in `call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
  /usr/local/bundle/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
  /usr/local/bundle/gems/skylight-core-4.1.2/lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
  /usr/local/bundle/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
  /usr/local/bundle/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
  /usr/local/bundle/gems/activesupport-6.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
  /usr/local/bundle/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
  /usr/local/bundle/gems/actionpack-6.0.0/lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
  /usr/local/bundle/gems/hirefire-resource-0.7.2/lib/hirefire/middleware.rb:38:in `call'
  /usr/local/bundle/gems/railties-6.0.0/lib/rails/engine.rb:526:in `call'
  /usr/local/bundle/gems/puma-4.1.1/lib/puma/configuration.rb:228:in `call'
  /usr/local/bundle/gems/puma-4.1.1/lib/puma/server.rb:664:in `handle_request'
  /usr/local/bundle/gems/puma-4.1.1/lib/puma/server.rb:467:in `process_client'
  /usr/local/bundle/gems/puma-4.1.1/lib/puma/server.rb:328:in `block in run'
  /usr/local/bundle/gems/puma-4.1.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

🎯 **Goal**

Run a usable instance of Octobox.

💡 **Possible solutions**

I'd prefer to see individually-tagged container builds - I don't like using 'latest' images as each time you pull it it is likely to be different - there's no guaranteed state. I'd rather pin to a known version and then upgrade when it suits me.

**Comment by glitchcrab** [comment]
after reading some other issues, i discovered the issue i'm having would be solved by this PR https://github.com/octobox/octobox/pull/1141

**Comment by ntimo** [comment]
I am having the same problem :( Can someone please merge this PR :) Thanks
