### ISSUE TITLE
Cannot modify Frozen String

### ISSUE THREAD

**Issue by jules2689** [octobox/octobox#2757]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance
 
If your issue is related to an Octobox.io subscription purchase please ensure you have installed the [Octobox GitHub App](https://github.com/apps/octobox) for the repositories concerned.

🐞 **Problem**

```
2021-08-16T15:22:58.888053+00:00 app[worker.2]: pid=4 tid=3ius WARN: FrozenError: can't modify frozen String: "Q"

2021-08-16T15:22:58.888085+00:00 app[worker.2]: pid=4 tid=3ius WARN: /app/app/models/notification.rb:39:in `delete!'

2021-08-16T15:22:58.888085+00:00 app[worker.2]: /app/app/models/notification.rb:39:in `block in attributes_from_api_response'

2021-08-16T15:22:58.888085+00:00 app[worker.2]: /app/app/models/notification.rb:37:in `each'

2021-08-16T15:22:58.888086+00:00 app[worker.2]: /app/app/models/notification.rb:37:in `map'

2021-08-16T15:22:58.888086+00:00 app[worker.2]: /app/app/models/notification.rb:37:in `attributes_from_api_response'

2021-08-16T15:22:58.888086+00:00 app[worker.2]: /app/app/models/notification.rb:152:in `update_from_api_response'

2021-08-16T15:22:58.888087+00:00 app[worker.2]: /app/app/services/download_service.rb:65:in `block in process_notifications'

2021-08-16T15:22:58.888087+00:00 app[worker.2]: /app/app/services/download_service.rb:60:in `each'

2021-08-16T15:22:58.888087+00:00 app[worker.2]: /app/app/services/download_service.rb:60:in `process_notifications'

2021-08-16T15:22:58.888088+00:00 app[worker.2]: /app/app/services/download_service.rb:47:in `fetch_new_notifications'

2021-08-16T15:22:58.888088+00:00 app[worker.2]: /app/app/services/download_service.rb:26:in `download'
```

🎯 **Goal**

Should not throw an exception

💡 **Possible solutions**

Dup the string if frozen

**Comment by andrew** [comment]
Related bug that I ran into, latest version of Oj broke lots of tests, here's how I fixed it: https://github.com/octobox/octobox/commit/ab845d84f01d091d75ae0c4379b0c230da94d4af

**Comment by jules2689** [comment]
We are using that on our instance too. Still seem to need the attached PR on this one
