### ISSUE TITLE
It errors on me

### ISSUE THREAD

**Issue by errordeveloper** [octobox/octobox#311]
Dunnot if I have too much activity or not, but would like to help debugging.

**Comment by tarebyte** [comment]
@errordeveloper do you remember what you were doing when it errored on you?

**Comment by errordeveloper** [comment]
Just trying to signup.

Re-tesed it with cookies cleared.

![](https://www.dropbox.com/s/25hujkod6uzoy94/Screenshot%202017-02-15%2006.46.47.png?dl=1)

![](https://www.dropbox.com/s/h427skkvkvpbhgv/Screenshot%202017-02-15%2006.46.58.png?dl=1)

Also tesed in Chrome, same problem. Here are the headers that may help to debug this. I couldn't find request details in Safari, but thought it may be a good idea to also test with Chrome, so here are the the headers I've copied from Chrome, I can see stuff like `cf-ray` and `x-request-id`, which both seem like potentially useful bits of info to trace this back via logs or whatever...

```
Request URL:https://octobox.io/auth/github/callback?code=20fbe9394da10fc5547e&state=3fe217c788991e2f83d7b1f99482c306e419d9d79cd408d3
Request Method:GET
Status Code:500 
Remote Address:104.31.92.138:443
Response Headers
cf-ray:3316d2188b9535c6-LHR
content-type:text/html; charset=utf-8
date:Wed, 15 Feb 2017 06:49:48 GMT
server:cloudflare-nginx
status:500
via:1.1 vegur
x-request-id:964d4a2a-5b59-4f2d-824c-77746914c1df
x-runtime:13.480903
Request Headers
:authority:octobox.io
:method:GET
:path:/auth/github/callback?code=20fbe9394da10fc5547e&state=3fe217c788991e2f83d7b1f99482c306e419d9d79cd408d3
:scheme:https
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding:gzip, deflate, sdch, br
accept-language:en-US,en;q=0.8,ru;q=0.6,en-GB;q=0.4
cache-control:no-cache
cookie:__cfduid=d5cb25cbbf9d2dbb1d37fd109586fbcd01487141345; _octobox_session=TDhTOUpSVjZ3NW9xS3FNSzhESCt0TXowZ3c3bkdLS1VYalR6TXUzRURZdUFySGtpeittREVqbjZQWEkzTjN1enBJUm9YalpkVXdrblRtQ1dRK3NnVDFzNDV4Ynkrek1JaURCSkZKbUxrcDdxQmhUeDd6czA1ak1QTGFMVFR1bVFucnNKanlpREgxK2FKZGxEcWdPZENxcmN0c3o1aHN5dXZ4MDdjd21zaVdkZ3NHc0dibmxicW9WS3pCMDBlZGJ3NmFBWjBuK1YxMU1KUUwrWUlNVm5YRkUwckhxUmt1MDgwZU9xRkVsM1RaOFRqUjBaSDRES0dOMG1pbWdUQ0dNWFByTURjdmdxbWM3NHlBRFlJNkdVK0hUWllkeE9sZDc0aGFUV1RVTEZMNnlGaEtuVWl5dGE2SW5FTm1GYTljQjUrUWRONE8wRWRmbHlwWWNQb25PV01RPT0tLVdDcHBXRVhjS05jWE5JeDM5UjlmRUE9PQ%3D%3D--c01366bc9b87cbf313b8b7b8f302d9e64e3598ff
pragma:no-cache
referer:https://octobox.io/login
upgrade-insecure-requests:1
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Query String Parameters
view source
view URL encoded
code:20fbe9394da10fc5547e
state:3fe217c788991e2f83d7b1f99482c306e419d9d79cd408d3
```

**Comment by errordeveloper** [comment]
I've also revoked and re-authorised the app, and test again with no luck.

**Comment by stevebosworth** [comment]
Happens to me as well :-( 

Tried revoking the app as well.  Tested in  FF and Chrome

**Comment by andrew** [comment]
I can see occasional 503 errors from the GitHub API servers when people are logging in, nothing we can fix there from our end, I'd recommend retrying a few times in a row.

**Comment by errordeveloper** [comment]
Hm... Surely something can be done. I'll install it on Heroku and try to debug myself. Will keep you posted.

**Comment by errordeveloper** [comment]
Ok, here's what I see in the logs on Heroku:
```
2017-03-09T11:29:40.413976+00:00 app[web.1]: I, [2017-03-09T11:29:40.413879 #9]  INFO -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4] Started GET "/auth/github/callback?code=2ed53d465825972a0f7d&state=de59bbee84a850121def2b54a2b47a6a316f1d28faacf804" for 81.109.250.113 at 2017-03-09 11:29:40 +0000
2017-03-09T11:29:40.414720+00:00 app[web.1]: I, [2017-03-09T11:29:40.414666 #9]  INFO -- omniauth: (github) Callback phase initiated.
2017-03-09T11:29:41.228262+00:00 app[web.1]: I, [2017-03-09T11:29:41.228145 #9]  INFO -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4] Processing by SessionsController#create as HTML
2017-03-09T11:29:41.228343+00:00 app[web.1]: I, [2017-03-09T11:29:41.228276 #9]  INFO -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4]   Parameters: {"code"=>"2ed53d465825972a0f7d", "state"=>"de59bbee84a850121def2b54a2b47a6a316f1d28faacf804", "provider"=>"github"}
2017-03-09T11:29:41.235154+00:00 app[web.1]: D, [2017-03-09T11:29:41.235046 #9] DEBUG -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4]   User Load (1.1ms)  SELECT  "users".* FROM "users" WHERE "users"."github_id" = $1 LIMIT $2  [["github_id", 251467], ["LIMIT", 1]]
2017-03-09T11:29:41.270768+00:00 app[web.1]: D, [2017-03-09T11:29:41.270601 #9] DEBUG -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4]    (0.9ms)  BEGIN
2017-03-09T11:29:41.278281+00:00 app[web.1]: D, [2017-03-09T11:29:41.278098 #9] DEBUG -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4]   User Exists (0.9ms)  SELECT  1 AS one FROM "users" WHERE "users"."github_id" = $1 LIMIT $2  [["github_id", 251467], ["LIMIT", 1]]
2017-03-09T11:29:41.280624+00:00 app[web.1]: D, [2017-03-09T11:29:41.280502 #9] DEBUG -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4]   User Exists (1.0ms)  SELECT  1 AS one FROM "users" WHERE "users"."access_token" = $1 LIMIT $2  [["access_token", "86e331a8e6fd95637da5d2f957463385affe78a7"], ["LIMIT", 1]]
2017-03-09T11:29:41.284704+00:00 app[web.1]: D, [2017-03-09T11:29:41.284605 #9] DEBUG -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4]   SQL (1.4ms)  INSERT INTO "users" ("github_id", "access_token", "github_login", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["github_id", 251467], ["access_token", "86e331a8e6fd95637da5d2f957463385affe78a7"], ["github_login", "errordeveloper"], ["created_at", 2017-03-09 11:29:41 UTC], ["updated_at", 2017-03-09 11:29:41 UTC]]
2017-03-09T11:29:41.298894+00:00 app[web.1]: D, [2017-03-09T11:29:41.298773 #9] DEBUG -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4]    (13.4ms)  COMMIT
2017-03-09T11:29:41.990151+00:00 app[web.1]: [4] PumaWorkerKiller: Consuming 240.49609375 mb with master and 2 workers.
2017-03-09T11:29:46.990738+00:00 app[web.1]: [4] PumaWorkerKiller: Consuming 272.921875 mb with master and 2 workers.
2017-03-09T11:29:51.991265+00:00 app[web.1]: [4] PumaWorkerKiller: Consuming 272.921875 mb with master and 2 workers.
2017-03-09T11:29:54.885518+00:00 app[web.1]: I, [2017-03-09T11:29:54.885419 #9]  INFO -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4] Completed 500 Internal Server Error in 13657ms (ActiveRecord: 24.0ms)
2017-03-09T11:29:54.886473+00:00 app[web.1]: W, [2017-03-09T11:29:54.886405 #9]  WARN -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4] ** [Bugsnag] No API key configured, couldn't notify
2017-03-09T11:29:54.891749+00:00 app[web.1]: F, [2017-03-09T11:29:54.887668 #9] FATAL -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4]   
2017-03-09T11:29:54.891807+00:00 app[web.1]: F, [2017-03-09T11:29:54.891762 #9] FATAL -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4] Octokit::ServiceUnavailable (GET https://api.github.com/notifications?all=true&page=6&per_page=100: 503 - Server Error // See: https://developer.github.com/v3):
2017-03-09T11:29:54.891846+00:00 app[web.1]: F, [2017-03-09T11:29:54.891810 #9] FATAL -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4]   
2017-03-09T11:29:54.891914+00:00 app[web.1]: F, [2017-03-09T11:29:54.891864 #9] FATAL -- : [10d70f57-efb3-40ad-b061-87ee66fcb5f4] app/services/download_service.rb:110:in `paginate'
2017-03-09T11:29:54.891916+00:00 app[web.1]: [10d70f57-efb3-40ad-b061-87ee66fcb5f4] app/services/download_service.rb:54:in `fetch_notifications'
2017-03-09T11:29:54.891916+00:00 app[web.1]: [10d70f57-efb3-40ad-b061-87ee66fcb5f4] app/services/download_service.rb:76:in `new_user_fetch'
2017-03-09T11:29:54.891916+00:00 app[web.1]: [10d70f57-efb3-40ad-b061-87ee66fcb5f4] app/services/download_service.rb:86:in `download'
2017-03-09T11:29:54.891917+00:00 app[web.1]: [10d70f57-efb3-40ad-b061-87ee66fcb5f4] app/models/user.rb:51:in `sync_notifications'
2017-03-09T11:29:54.891917+00:00 app[web.1]: [10d70f57-efb3-40ad-b061-87ee66fcb5f4] app/controllers/sessions_controller.rb:14:in `create'
2017-03-09T11:29:54.892424+00:00 heroku[router]: at=info method=GET path="/auth/github/callback?code=2ed53d465825972a0f7d&state=de59bbee84a850121def2b54a2b47a6a316f1d28faacf804" host=errordeveloper-octobox.herokuapp.com request_id=10d70f57-efb3-40ad-b061-87ee66fcb5f4 fwd="81.109.250.113" dyno=web.1 connect=0ms service=14481ms status=500 bytes=1689 protocol=https
```

**Comment by errordeveloper** [comment]
Ok, I've just tested it with `curl` and got a 500 from `https://api.github.com/notifications?all=true&page=6&per_page=100` on a 3rd attempt. Clearly we just need to retry on 500, right?

**Comment by errordeveloper** [comment]
Ok, I've set `MAX_NOTIFICATIONS_TO_SYNC=200` on my Heroku deployment and finally been able to login.

**Comment by andrew** [comment]
@errordeveloper I'm gunna close this as you've been able to login now

**Comment by errordeveloper** [comment]
Well, not on the octobox.io, but only on my own deployment of a fork of the
project...
