### ISSUE TITLE
Latest version from docker-compose pull fails to launch

### ISSUE THREAD

**Issue by osdlge** [octobox/octobox#524]
I just did a ```docker-compose pull``` to grab the latest revision and it fails to start

Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [ x] My instance

🐞 **Problem**
The output from the logs shows
```
Starting octobox_app_1 ...
Starting octobox_app_1 ... done
Attaching to octobox_database.service.octobox.internal_1, octobox_app_1
database.service.octobox.internal_1  | LOG:  database system was shut down at 2018-01-11 13:52:42 UTC
database.service.octobox.internal_1  | LOG:  MultiXact member wraparound protections are now enabled
database.service.octobox.internal_1  | LOG:  database system is ready to accept connections
database.service.octobox.internal_1  | LOG:  autovacuum launcher started
database.service.octobox.internal_1  | LOG:  incomplete startup packet
database.service.octobox.internal_1  | FATAL:  password authentication failed for user "root"
database.service.octobox.internal_1  | DETAIL:  Role "root" does not exist.
database.service.octobox.internal_1  | 	Connection matched pg_hba.conf line 95: "host all all all md5"
app_1                                | rake aborted!
app_1                                | PG::ConnectionBad: FATAL:  password authentication failed for user "root"
app_1                                | /usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `initialize'
app_1                                | /usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `new'
app_1                                | /usr/local/bundle/gems/pg-0.21.0/lib/pg.rb:56:in `connect'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:695:in `connect'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:220:in `initialize'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `new'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/postgresql_adapter.rb:38:in `postgresql_connection'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:759:in `new_connection'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:803:in `checkout_new_connection'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:782:in `try_to_checkout_new_connection'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:743:in `acquire_connection'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:500:in `checkout'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:374:in `connection'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `retrieve_connection'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:116:in `retrieve_connection'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:88:in `connection'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/schema_migration.rb:20:in `table_exists?'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/schema_migration.rb:24:in `create_table'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/migration.rb:1125:in `initialize'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `new'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
app_1                                | /usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
app_1                                | /usr/local/bundle/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
app_1                                | /usr/local/bundle/bin/bundle:104:in `load'
app_1                                | /usr/local/bundle/bin/bundle:104:in `<main>'
app_1                                | Tasks: TOP => db:migrate
app_1                                | (See full trace by running task with --trace)
octobox_app_1 exited with code 1
```

looks like there is some problem with the password to connect to the database

**Comment by osdlge** [comment]
This can be closed, looked through the commits and found this

https://github.com/octobox/octobox/commit/684f9494244ae3b2648b1a949a49447b5837ea5c#diff-4e5e90c6228fd48698d074241c2ba760R20

I updated my .yml file to the new USERNAME and it started working

Thanks!
