### ISSUE TITLE
Select all is not working

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#755]
Are you experiencing this issue in octobox.io or your own instance?
 - [x] octobox.io
 - [ ] My instance

🐞 **Problem**
Clicking on the select all check box does not do anything.

<img width="996" alt="screen shot 2018-08-08 at 11 25 27 am" src="https://user-images.githubusercontent.com/3275593/43818767-c80c35f0-9afd-11e8-9b43-cb373a665c61.png">

Clicking the first checkbox should select the all notifications but it does not. Instead, nothing happens (even the checkbox itself doesn't get checked)

PS: Ignore the style changes; they are unrelated to this; verified by disabling the injection.

**Comment by andrew** [comment]
I think I fixed this yesterday but haven’t deployed it yet: https://github.com/octobox/octobox/commit/c8712bcbd7b60406f873fa74f0b7c92b738ee146

**Comment by pradyunsg** [comment]
Cool. I guess we can keep this open until this gets deployed. :)

**Comment by andrew** [comment]
Just deployed, wanna give it a try? Looks like it’s working for me

**Comment by pradyunsg** [comment]
We're good. Thanks @andrew! :)

**Comment by pradyunsg** [comment]
Oh oh oh. While I have your attention here, do you know of any way for me to deploy a personal instance of octobox on a cloud service for free?

I tried deploying to the free tier on OpenShift/Heroku but they both need more add-ons than the free tier allows.

**Comment by andrew** [comment]
I’m running a free version on heroku, which addon does it look like it needs?

**Comment by pradyunsg** [comment]
Hmm... It seems like all of them are free add ons. I'll try again when I find some time. I'll let you know how it goes? (exam week is coming!)

**Comment by pradyunsg** [comment]
Ah right. It needed me to verify a credit card; which I didn't want to do to avoid accidentally doing something that ends up costing me money.

Just added that. Let's see how it goes. :P

**Comment by andrew** [comment]
Great! Good luck with your exams!

**Comment by pradyunsg** [comment]
https://pradyunsg-octobox.herokuapp.com/ errors out. Got no time to look into where what messed up.

> Good luck with your exams!

Thanks! ^.^

**Comment by andrew** [comment]
Sure, heroku logs —tail should show the exception

**Comment by pradyunsg** [comment]
In the Web UI at https://dashboard.heroku.com/apps/pradyunsg-octobox/logs:

```
2018-08-11T08:35:29.180511+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
2018-08-11T08:35:29.180513+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'
2018-08-11T08:35:29.180514+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:410:in `run'
2018-08-11T08:35:29.180515+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
2018-08-11T08:35:29.180517+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
2018-08-11T08:35:29.180518+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
2018-08-11T08:35:29.180519+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
2018-08-11T08:35:29.180520+00:00 app[web.1]:   /app/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
2018-08-11T08:35:31+00:00 app[heroku-redis]: source=REDIS addon=redis-horizontal-25020 sample#active-connections=1 sample#load-avg-1m=0.07 sample#load-avg-5m=0.09 sample#load-avg-15m=0.085 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664360kB sample#memory-free=11645700kB sample#memory-cached=935780kB sample#memory-redis=278200bytes sample#hit-rate=1 sample#evicted-keys=0
2018-08-11T08:35:31+00:00 app[heroku-redis]: source=REDIS addon=redis-horizontal-25020 sample#active-connections=1 sample#load-avg-1m=0.125 sample#load-avg-5m=0.1 sample#load-avg-15m=0.09 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664360kB sample#memory-free=11646368kB sample#memory-cached=935784kB sample#memory-redis=278200bytes sample#hit-rate=1 sample#evicted-keys=0
```

**Comment by pradyunsg** [comment]
That's probably an incomplete traceback.

Anyway, I see this:

```
2018-08-11T08:39:52.809735+00:00 app[web.1]: ArgumentError: Must provide a 32 byte encryption key as the env var OCTOBOX_ATTRIBUTE_ENCRYPTION_KEY
```

I'm bad at counting, and only gave it a 16 byte key. :)

**Comment by pradyunsg** [comment]
Okay, no. That was 256 bits, so, that's 32 bytes.

@andrew Could you provide an example of what format the `OCTOBOX_ATTRIBUTE_ENCRYPTION_KEY` should be in?

**Comment by andrew** [comment]
Handy command to generate a key: `bin/rails secret | cut -c1-32`

**Comment by pradyunsg** [comment]
Alrighty. I'm up.

ISTM that due to the following lines, it should be possible to just run w/o this variable being declared. I just tried that on my Heroku setup and it seems to be happy with this. :)

https://github.com/octobox/octobox/blob/24e813ee42a32da1a07da7c1d10b8395bc4239fc/lib/octobox/configurator.rb#L3-L16

---

I tried to use `bin/rails secret | cut -c1-32` but it needed me to do a whole bunch of extra steps to actually get rails running on a local clone of octobox. I gave up midway (due to time constraints). :/

Ideally, there should be a method that doesn't involve creating a complete development environment for octobox to generate the random key. Should this become a new PR/issue?

---

Hurrah! I have my own Octobox instance! Thanks for the help @andrew! ^>^

**Comment by andrew** [comment]
A pr for that would be great!

**Comment by pradyunsg** [comment]
Could you provide some example value of `OCTOBOX_ATTRIBUTE_ENCRYPTION_KEY`?

**Comment by andrew** [comment]
@pradyunsg `05cb88ad4bf8a7a3a5b0c53aaf181c16`
