### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by pradyunsg** [octobox/octobox#809]
Are you experiencing this issue in octobox.io or your own instance?
 - [ ] octobox.io
 - [x] My instance

🐞 **Problem**
Octobox crashes while trying to sync.

```
<time>.568338+00:00 app[web.1]: I, [<time>.568214 #30]  INFO -- : [<redact>] method=POST path=/notifications/sync format=html controller=NotificationsController action=sync status=500 error='ActiveModel::UnknownAttributeError: unknown attribute 'node_id' for Repository.' duration=499.26 view=0.00 db=13.07
<time>.569878+00:00 app[web.1]: F, [<time>.569799 #30] FATAL -- : [<redact>]
<time>.569989+00:00 app[web.1]: F, [<time>.569921 #30] FATAL -- : [<redact>] ActiveModel::UnknownAttributeError (unknown attribute 'node_id' for Repository.):
<time>.570054+00:00 app[web.1]: F, [<time>.569990 #30] FATAL -- : [<redact>]
<time>.570161+00:00 app[web.1]: F, [<time>.570093 #30] FATAL -- : [<redact>] app/models/notification.rb:224:in `update_repository'
<time>.570163+00:00 app[web.1]: [<redact>] app/models/notification.rb:139:in `update_from_api_response'
<time>.570164+00:00 app[web.1]: [<redact>] app/services/download_service.rb:74:in `block in process_notifications'
<time>.570166+00:00 app[web.1]: [<redact>] app/services/download_service.rb:69:in `each'
<time>.570167+00:00 app[web.1]: [<redact>] app/services/download_service.rb:69:in `process_notifications'
<time>.570168+00:00 app[web.1]: [<redact>] app/services/download_service.rb:61:in `fetch_read_notifications'
<time>.570170+00:00 app[web.1]: [<redact>] app/services/download_service.rb:28:in `download'
<time>.570171+00:00 app[web.1]: [<redact>] app/models/user.rb:59:in `sync_notifications'
<time>.570172+00:00 app[web.1]: [<redact>] app/controllers/notifications_controller.rb:206:in `sync'
```

🎯 **Goal**
It should not crash. :)

**Comment by andrew** [comment]
@pradyunsg sorry about that, my bad, just pushed a quick fix to master

**Comment by pradyunsg** [comment]
No issues.

Heroku makes it easy to re-deploy a known good version so, I basically had to spend about 1 minute after posting these logs to get back up. Much more than the time Octobox has saved me till date. :)

**Comment by andrew** [comment]
@pradyunsg locking this for testing reasons ;)
